name: cd

on:
  push:
    branches:
      [main]
    paths:
      - '**.py'
      - '**.sh'
      - '**.sql'
      - '**Dockerfile'

jobs:
  push-image:
    name: Push Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Push to GCP
        run: gcloud builds submit --tag ${{ secrets.GCP_ARTIFACT_IMAGE }}:latest

  deploy-crawler:
    name: Deploy-Crawler
    runs-on: ubuntu-latest
    needs: [push-image]

    env:
      CMC_PRO_API_KEY: ${{ secrets.CMC_PRO_API_KEY }}
      TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      DB_URL: ${{ secrets.DB_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Database Migration
        run: goose -dir sql/schema turso "${{ secrets.DB_URL }}?authToken=${{ secrets.TURSO_AUTH_TOKEN }}" up

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Update Cloud Run Job
        run: |
          gcloud run jobs update crypto-craig-crawler-job \
            --image ${{ secrets.GCP_ARTIFACT_IMAGE }}:latest \
            --region us-central1 \
            --set-env-vars "CMC_PRO_API_KEY=${CMC_PRO_API_KEY},TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN},DB_URL=${DB_URL}" \
            --command "python3,main.py,crawler,job"

  deploy-craig:
    name: Deploy-Craig
    runs-on: ubuntu-latest
    needs: [push-image]

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Prune Images
        run: gcloud compute ssh smol-bean --zone us-central1-a --command "docker image prune -f -a"

      - name: Update Container
        run: |
          gcloud compute instances update-container smol-bean \
            --zone us-central1-a \
            --container-image ${{ secrets.GCP_ARTIFACT_IMAGE }}:latest \
            --container-command python3 \
            --container-arg main.py \
            --container-arg craig \